import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { Controls } from './Controls'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '환영합니다. NextJS',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics/',{cache: 'no-store'});
  const topics = await resp.json();

  return (
    <html lang="kr">
      <body className={inter.className} style={{padding: 20}} >
      <h1><Link href='/'>Home</Link></h1>
      <ol className='flex flex-row gap-5 mb-5 bg-yellow-600 rounded-full justify-between px-5'>
        {topics.map((topic) =>{
          return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>          
        })}
        {/* <li><Link href='/read/1'>html</Link></li>
        <li><Link href='/read/2'>css</Link></li> */}
      </ol>
        {children}
        <Controls/>  
      </body>
    </html>
  )
}
